// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/mgmntv1/movies.proto

package mgmntv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MovieManagementService_AddMovie_FullMethodName               = "/muxcore.media.movies.v1.MovieManagementService/AddMovie"
	MovieManagementService_RemoveMovie_FullMethodName            = "/muxcore.media.movies.v1.MovieManagementService/RemoveMovie"
	MovieManagementService_RefreshMetadata_FullMethodName        = "/muxcore.media.movies.v1.MovieManagementService/RefreshMetadata"
	MovieManagementService_ListMovies_FullMethodName             = "/muxcore.media.movies.v1.MovieManagementService/ListMovies"
	MovieManagementService_ListMissing_FullMethodName            = "/muxcore.media.movies.v1.MovieManagementService/ListMissing"
	MovieManagementService_GetMovie_FullMethodName               = "/muxcore.media.movies.v1.MovieManagementService/GetMovie"
	MovieManagementService_UpdateMovie_FullMethodName            = "/muxcore.media.movies.v1.MovieManagementService/UpdateMovie"
	MovieManagementService_AddFile_FullMethodName                = "/muxcore.media.movies.v1.MovieManagementService/AddFile"
	MovieManagementService_RemoveFile_FullMethodName             = "/muxcore.media.movies.v1.MovieManagementService/RemoveFile"
	MovieManagementService_ListFiles_FullMethodName              = "/muxcore.media.movies.v1.MovieManagementService/ListFiles"
	MovieManagementService_CreateTag_FullMethodName              = "/muxcore.media.movies.v1.MovieManagementService/CreateTag"
	MovieManagementService_DeleteTag_FullMethodName              = "/muxcore.media.movies.v1.MovieManagementService/DeleteTag"
	MovieManagementService_ListTags_FullMethodName               = "/muxcore.media.movies.v1.MovieManagementService/ListTags"
	MovieManagementService_SetItemTags_FullMethodName            = "/muxcore.media.movies.v1.MovieManagementService/SetItemTags"
	MovieManagementService_ListCollections_FullMethodName        = "/muxcore.media.movies.v1.MovieManagementService/ListCollections"
	MovieManagementService_GetCollectionMovies_FullMethodName    = "/muxcore.media.movies.v1.MovieManagementService/GetCollectionMovies"
	MovieManagementService_ListAlternateTitles_FullMethodName    = "/muxcore.media.movies.v1.MovieManagementService/ListAlternateTitles"
	MovieManagementService_AddAlternateTitle_FullMethodName      = "/muxcore.media.movies.v1.MovieManagementService/AddAlternateTitle"
	MovieManagementService_RemoveAlternateTitle_FullMethodName   = "/muxcore.media.movies.v1.MovieManagementService/RemoveAlternateTitle"
	MovieManagementService_ListTrailers_FullMethodName           = "/muxcore.media.movies.v1.MovieManagementService/ListTrailers"
	MovieManagementService_SetCollectionMonitored_FullMethodName = "/muxcore.media.movies.v1.MovieManagementService/SetCollectionMonitored"
	MovieManagementService_GetCollectionPrefs_FullMethodName     = "/muxcore.media.movies.v1.MovieManagementService/GetCollectionPrefs"
	MovieManagementService_SyncCollection_FullMethodName         = "/muxcore.media.movies.v1.MovieManagementService/SyncCollection"
)

// MovieManagementServiceClient is the client API for MovieManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieManagementServiceClient interface {
	AddMovie(ctx context.Context, in *AddMovieRequest, opts ...grpc.CallOption) (*AddMovieResponse, error)
	RemoveMovie(ctx context.Context, in *RemoveMovieRequest, opts ...grpc.CallOption) (*RemoveMovieResponse, error)
	RefreshMetadata(ctx context.Context, in *RefreshMetadataRequest, opts ...grpc.CallOption) (*RefreshMetadataResponse, error)
	ListMovies(ctx context.Context, in *ListMoviesRequest, opts ...grpc.CallOption) (*ListMoviesResponse, error)
	ListMissing(ctx context.Context, in *ListMissingRequest, opts ...grpc.CallOption) (*ListMissingResponse, error)
	GetMovie(ctx context.Context, in *GetMovieRequest, opts ...grpc.CallOption) (*GetMovieResponse, error)
	UpdateMovie(ctx context.Context, in *UpdateMovieRequest, opts ...grpc.CallOption) (*UpdateMovieResponse, error)
	AddFile(ctx context.Context, in *AddFileRequest, opts ...grpc.CallOption) (*AddFileResponse, error)
	RemoveFile(ctx context.Context, in *RemoveFileRequest, opts ...grpc.CallOption) (*RemoveFileResponse, error)
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error)
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error)
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
	SetItemTags(ctx context.Context, in *SetItemTagsRequest, opts ...grpc.CallOption) (*SetItemTagsResponse, error)
	ListCollections(ctx context.Context, in *ListCollectionsRequest, opts ...grpc.CallOption) (*ListCollectionsResponse, error)
	GetCollectionMovies(ctx context.Context, in *GetCollectionMoviesRequest, opts ...grpc.CallOption) (*GetCollectionMoviesResponse, error)
	ListAlternateTitles(ctx context.Context, in *ListAlternateTitlesRequest, opts ...grpc.CallOption) (*ListAlternateTitlesResponse, error)
	AddAlternateTitle(ctx context.Context, in *AddAlternateTitleRequest, opts ...grpc.CallOption) (*AddAlternateTitleResponse, error)
	RemoveAlternateTitle(ctx context.Context, in *RemoveAlternateTitleRequest, opts ...grpc.CallOption) (*RemoveAlternateTitleResponse, error)
	ListTrailers(ctx context.Context, in *ListTrailersRequest, opts ...grpc.CallOption) (*ListTrailersResponse, error)
	SetCollectionMonitored(ctx context.Context, in *SetCollectionMonitoredRequest, opts ...grpc.CallOption) (*SetCollectionMonitoredResponse, error)
	GetCollectionPrefs(ctx context.Context, in *GetCollectionPrefsRequest, opts ...grpc.CallOption) (*GetCollectionPrefsResponse, error)
	SyncCollection(ctx context.Context, in *SyncCollectionRequest, opts ...grpc.CallOption) (*SyncCollectionResponse, error)
}

type movieManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieManagementServiceClient(cc grpc.ClientConnInterface) MovieManagementServiceClient {
	return &movieManagementServiceClient{cc}
}

func (c *movieManagementServiceClient) AddMovie(ctx context.Context, in *AddMovieRequest, opts ...grpc.CallOption) (*AddMovieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMovieResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_AddMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) RemoveMovie(ctx context.Context, in *RemoveMovieRequest, opts ...grpc.CallOption) (*RemoveMovieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMovieResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_RemoveMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) RefreshMetadata(ctx context.Context, in *RefreshMetadataRequest, opts ...grpc.CallOption) (*RefreshMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshMetadataResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_RefreshMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) ListMovies(ctx context.Context, in *ListMoviesRequest, opts ...grpc.CallOption) (*ListMoviesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMoviesResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_ListMovies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) ListMissing(ctx context.Context, in *ListMissingRequest, opts ...grpc.CallOption) (*ListMissingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMissingResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_ListMissing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) GetMovie(ctx context.Context, in *GetMovieRequest, opts ...grpc.CallOption) (*GetMovieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMovieResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_GetMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) UpdateMovie(ctx context.Context, in *UpdateMovieRequest, opts ...grpc.CallOption) (*UpdateMovieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMovieResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_UpdateMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) AddFile(ctx context.Context, in *AddFileRequest, opts ...grpc.CallOption) (*AddFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFileResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_AddFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) RemoveFile(ctx context.Context, in *RemoveFileRequest, opts ...grpc.CallOption) (*RemoveFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFileResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_RemoveFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTagResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_CreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTagResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_DeleteTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) SetItemTags(ctx context.Context, in *SetItemTagsRequest, opts ...grpc.CallOption) (*SetItemTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetItemTagsResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_SetItemTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) ListCollections(ctx context.Context, in *ListCollectionsRequest, opts ...grpc.CallOption) (*ListCollectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollectionsResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_ListCollections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) GetCollectionMovies(ctx context.Context, in *GetCollectionMoviesRequest, opts ...grpc.CallOption) (*GetCollectionMoviesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCollectionMoviesResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_GetCollectionMovies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) ListAlternateTitles(ctx context.Context, in *ListAlternateTitlesRequest, opts ...grpc.CallOption) (*ListAlternateTitlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlternateTitlesResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_ListAlternateTitles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) AddAlternateTitle(ctx context.Context, in *AddAlternateTitleRequest, opts ...grpc.CallOption) (*AddAlternateTitleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAlternateTitleResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_AddAlternateTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) RemoveAlternateTitle(ctx context.Context, in *RemoveAlternateTitleRequest, opts ...grpc.CallOption) (*RemoveAlternateTitleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveAlternateTitleResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_RemoveAlternateTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) ListTrailers(ctx context.Context, in *ListTrailersRequest, opts ...grpc.CallOption) (*ListTrailersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrailersResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_ListTrailers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) SetCollectionMonitored(ctx context.Context, in *SetCollectionMonitoredRequest, opts ...grpc.CallOption) (*SetCollectionMonitoredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCollectionMonitoredResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_SetCollectionMonitored_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) GetCollectionPrefs(ctx context.Context, in *GetCollectionPrefsRequest, opts ...grpc.CallOption) (*GetCollectionPrefsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCollectionPrefsResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_GetCollectionPrefs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) SyncCollection(ctx context.Context, in *SyncCollectionRequest, opts ...grpc.CallOption) (*SyncCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncCollectionResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_SyncCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieManagementServiceServer is the server API for MovieManagementService service.
// All implementations must embed UnimplementedMovieManagementServiceServer
// for forward compatibility.
type MovieManagementServiceServer interface {
	AddMovie(context.Context, *AddMovieRequest) (*AddMovieResponse, error)
	RemoveMovie(context.Context, *RemoveMovieRequest) (*RemoveMovieResponse, error)
	RefreshMetadata(context.Context, *RefreshMetadataRequest) (*RefreshMetadataResponse, error)
	ListMovies(context.Context, *ListMoviesRequest) (*ListMoviesResponse, error)
	ListMissing(context.Context, *ListMissingRequest) (*ListMissingResponse, error)
	GetMovie(context.Context, *GetMovieRequest) (*GetMovieResponse, error)
	UpdateMovie(context.Context, *UpdateMovieRequest) (*UpdateMovieResponse, error)
	AddFile(context.Context, *AddFileRequest) (*AddFileResponse, error)
	RemoveFile(context.Context, *RemoveFileRequest) (*RemoveFileResponse, error)
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	CreateTag(context.Context, *CreateTagRequest) (*CreateTagResponse, error)
	DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error)
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	SetItemTags(context.Context, *SetItemTagsRequest) (*SetItemTagsResponse, error)
	ListCollections(context.Context, *ListCollectionsRequest) (*ListCollectionsResponse, error)
	GetCollectionMovies(context.Context, *GetCollectionMoviesRequest) (*GetCollectionMoviesResponse, error)
	ListAlternateTitles(context.Context, *ListAlternateTitlesRequest) (*ListAlternateTitlesResponse, error)
	AddAlternateTitle(context.Context, *AddAlternateTitleRequest) (*AddAlternateTitleResponse, error)
	RemoveAlternateTitle(context.Context, *RemoveAlternateTitleRequest) (*RemoveAlternateTitleResponse, error)
	ListTrailers(context.Context, *ListTrailersRequest) (*ListTrailersResponse, error)
	SetCollectionMonitored(context.Context, *SetCollectionMonitoredRequest) (*SetCollectionMonitoredResponse, error)
	GetCollectionPrefs(context.Context, *GetCollectionPrefsRequest) (*GetCollectionPrefsResponse, error)
	SyncCollection(context.Context, *SyncCollectionRequest) (*SyncCollectionResponse, error)
	mustEmbedUnimplementedMovieManagementServiceServer()
}

// UnimplementedMovieManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMovieManagementServiceServer struct{}

func (UnimplementedMovieManagementServiceServer) AddMovie(context.Context, *AddMovieRequest) (*AddMovieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMovie not implemented")
}
func (UnimplementedMovieManagementServiceServer) RemoveMovie(context.Context, *RemoveMovieRequest) (*RemoveMovieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMovie not implemented")
}
func (UnimplementedMovieManagementServiceServer) RefreshMetadata(context.Context, *RefreshMetadataRequest) (*RefreshMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshMetadata not implemented")
}
func (UnimplementedMovieManagementServiceServer) ListMovies(context.Context, *ListMoviesRequest) (*ListMoviesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMovies not implemented")
}
func (UnimplementedMovieManagementServiceServer) ListMissing(context.Context, *ListMissingRequest) (*ListMissingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMissing not implemented")
}
func (UnimplementedMovieManagementServiceServer) GetMovie(context.Context, *GetMovieRequest) (*GetMovieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMovie not implemented")
}
func (UnimplementedMovieManagementServiceServer) UpdateMovie(context.Context, *UpdateMovieRequest) (*UpdateMovieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMovie not implemented")
}
func (UnimplementedMovieManagementServiceServer) AddFile(context.Context, *AddFileRequest) (*AddFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddFile not implemented")
}
func (UnimplementedMovieManagementServiceServer) RemoveFile(context.Context, *RemoveFileRequest) (*RemoveFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFile not implemented")
}
func (UnimplementedMovieManagementServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedMovieManagementServiceServer) CreateTag(context.Context, *CreateTagRequest) (*CreateTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedMovieManagementServiceServer) DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTag not implemented")
}
func (UnimplementedMovieManagementServiceServer) ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedMovieManagementServiceServer) SetItemTags(context.Context, *SetItemTagsRequest) (*SetItemTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetItemTags not implemented")
}
func (UnimplementedMovieManagementServiceServer) ListCollections(context.Context, *ListCollectionsRequest) (*ListCollectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCollections not implemented")
}
func (UnimplementedMovieManagementServiceServer) GetCollectionMovies(context.Context, *GetCollectionMoviesRequest) (*GetCollectionMoviesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCollectionMovies not implemented")
}
func (UnimplementedMovieManagementServiceServer) ListAlternateTitles(context.Context, *ListAlternateTitlesRequest) (*ListAlternateTitlesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAlternateTitles not implemented")
}
func (UnimplementedMovieManagementServiceServer) AddAlternateTitle(context.Context, *AddAlternateTitleRequest) (*AddAlternateTitleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAlternateTitle not implemented")
}
func (UnimplementedMovieManagementServiceServer) RemoveAlternateTitle(context.Context, *RemoveAlternateTitleRequest) (*RemoveAlternateTitleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAlternateTitle not implemented")
}
func (UnimplementedMovieManagementServiceServer) ListTrailers(context.Context, *ListTrailersRequest) (*ListTrailersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrailers not implemented")
}
func (UnimplementedMovieManagementServiceServer) SetCollectionMonitored(context.Context, *SetCollectionMonitoredRequest) (*SetCollectionMonitoredResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCollectionMonitored not implemented")
}
func (UnimplementedMovieManagementServiceServer) GetCollectionPrefs(context.Context, *GetCollectionPrefsRequest) (*GetCollectionPrefsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCollectionPrefs not implemented")
}
func (UnimplementedMovieManagementServiceServer) SyncCollection(context.Context, *SyncCollectionRequest) (*SyncCollectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncCollection not implemented")
}
func (UnimplementedMovieManagementServiceServer) mustEmbedUnimplementedMovieManagementServiceServer() {
}
func (UnimplementedMovieManagementServiceServer) testEmbeddedByValue() {}

// UnsafeMovieManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieManagementServiceServer will
// result in compilation errors.
type UnsafeMovieManagementServiceServer interface {
	mustEmbedUnimplementedMovieManagementServiceServer()
}

func RegisterMovieManagementServiceServer(s grpc.ServiceRegistrar, srv MovieManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedMovieManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MovieManagementService_ServiceDesc, srv)
}

func _MovieManagementService_AddMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).AddMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_AddMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).AddMovie(ctx, req.(*AddMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_RemoveMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).RemoveMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_RemoveMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).RemoveMovie(ctx, req.(*RemoveMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_RefreshMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).RefreshMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_RefreshMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).RefreshMetadata(ctx, req.(*RefreshMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_ListMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMoviesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).ListMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_ListMovies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).ListMovies(ctx, req.(*ListMoviesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_ListMissing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMissingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).ListMissing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_ListMissing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).ListMissing(ctx, req.(*ListMissingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_GetMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).GetMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_GetMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).GetMovie(ctx, req.(*GetMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_UpdateMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).UpdateMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_UpdateMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).UpdateMovie(ctx, req.(*UpdateMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_AddFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).AddFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_AddFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).AddFile(ctx, req.(*AddFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_RemoveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).RemoveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_RemoveFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).RemoveFile(ctx, req.(*RemoveFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_DeleteTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_SetItemTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetItemTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).SetItemTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_SetItemTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).SetItemTags(ctx, req.(*SetItemTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_ListCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCollectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).ListCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_ListCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).ListCollections(ctx, req.(*ListCollectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_GetCollectionMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionMoviesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).GetCollectionMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_GetCollectionMovies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).GetCollectionMovies(ctx, req.(*GetCollectionMoviesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_ListAlternateTitles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlternateTitlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).ListAlternateTitles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_ListAlternateTitles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).ListAlternateTitles(ctx, req.(*ListAlternateTitlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_AddAlternateTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAlternateTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).AddAlternateTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_AddAlternateTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).AddAlternateTitle(ctx, req.(*AddAlternateTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_RemoveAlternateTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAlternateTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).RemoveAlternateTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_RemoveAlternateTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).RemoveAlternateTitle(ctx, req.(*RemoveAlternateTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_ListTrailers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrailersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).ListTrailers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_ListTrailers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).ListTrailers(ctx, req.(*ListTrailersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_SetCollectionMonitored_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCollectionMonitoredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).SetCollectionMonitored(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_SetCollectionMonitored_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).SetCollectionMonitored(ctx, req.(*SetCollectionMonitoredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_GetCollectionPrefs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionPrefsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).GetCollectionPrefs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_GetCollectionPrefs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).GetCollectionPrefs(ctx, req.(*GetCollectionPrefsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_SyncCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).SyncCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_SyncCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).SyncCollection(ctx, req.(*SyncCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MovieManagementService_ServiceDesc is the grpc.ServiceDesc for MovieManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovieManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muxcore.media.movies.v1.MovieManagementService",
	HandlerType: (*MovieManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMovie",
			Handler:    _MovieManagementService_AddMovie_Handler,
		},
		{
			MethodName: "RemoveMovie",
			Handler:    _MovieManagementService_RemoveMovie_Handler,
		},
		{
			MethodName: "RefreshMetadata",
			Handler:    _MovieManagementService_RefreshMetadata_Handler,
		},
		{
			MethodName: "ListMovies",
			Handler:    _MovieManagementService_ListMovies_Handler,
		},
		{
			MethodName: "ListMissing",
			Handler:    _MovieManagementService_ListMissing_Handler,
		},
		{
			MethodName: "GetMovie",
			Handler:    _MovieManagementService_GetMovie_Handler,
		},
		{
			MethodName: "UpdateMovie",
			Handler:    _MovieManagementService_UpdateMovie_Handler,
		},
		{
			MethodName: "AddFile",
			Handler:    _MovieManagementService_AddFile_Handler,
		},
		{
			MethodName: "RemoveFile",
			Handler:    _MovieManagementService_RemoveFile_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _MovieManagementService_ListFiles_Handler,
		},
		{
			MethodName: "CreateTag",
			Handler:    _MovieManagementService_CreateTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _MovieManagementService_DeleteTag_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _MovieManagementService_ListTags_Handler,
		},
		{
			MethodName: "SetItemTags",
			Handler:    _MovieManagementService_SetItemTags_Handler,
		},
		{
			MethodName: "ListCollections",
			Handler:    _MovieManagementService_ListCollections_Handler,
		},
		{
			MethodName: "GetCollectionMovies",
			Handler:    _MovieManagementService_GetCollectionMovies_Handler,
		},
		{
			MethodName: "ListAlternateTitles",
			Handler:    _MovieManagementService_ListAlternateTitles_Handler,
		},
		{
			MethodName: "AddAlternateTitle",
			Handler:    _MovieManagementService_AddAlternateTitle_Handler,
		},
		{
			MethodName: "RemoveAlternateTitle",
			Handler:    _MovieManagementService_RemoveAlternateTitle_Handler,
		},
		{
			MethodName: "ListTrailers",
			Handler:    _MovieManagementService_ListTrailers_Handler,
		},
		{
			MethodName: "SetCollectionMonitored",
			Handler:    _MovieManagementService_SetCollectionMonitored_Handler,
		},
		{
			MethodName: "GetCollectionPrefs",
			Handler:    _MovieManagementService_GetCollectionPrefs_Handler,
		},
		{
			MethodName: "SyncCollection",
			Handler:    _MovieManagementService_SyncCollection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mgmntv1/movies.proto",
}
