// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/mgmntv1/movies.proto

package mgmntv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MovieManagementService_AddMovie_FullMethodName        = "/muxcore.media.movies.v1.MovieManagementService/AddMovie"
	MovieManagementService_RemoveMovie_FullMethodName     = "/muxcore.media.movies.v1.MovieManagementService/RemoveMovie"
	MovieManagementService_RefreshMetadata_FullMethodName = "/muxcore.media.movies.v1.MovieManagementService/RefreshMetadata"
	MovieManagementService_ListMovies_FullMethodName      = "/muxcore.media.movies.v1.MovieManagementService/ListMovies"
	MovieManagementService_GetMovie_FullMethodName        = "/muxcore.media.movies.v1.MovieManagementService/GetMovie"
	MovieManagementService_AddFile_FullMethodName         = "/muxcore.media.movies.v1.MovieManagementService/AddFile"
	MovieManagementService_RemoveFile_FullMethodName      = "/muxcore.media.movies.v1.MovieManagementService/RemoveFile"
	MovieManagementService_ListFiles_FullMethodName       = "/muxcore.media.movies.v1.MovieManagementService/ListFiles"
)

// MovieManagementServiceClient is the client API for MovieManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieManagementServiceClient interface {
	AddMovie(ctx context.Context, in *AddMovieRequest, opts ...grpc.CallOption) (*AddMovieResponse, error)
	RemoveMovie(ctx context.Context, in *RemoveMovieRequest, opts ...grpc.CallOption) (*RemoveMovieResponse, error)
	RefreshMetadata(ctx context.Context, in *RefreshMetadataRequest, opts ...grpc.CallOption) (*RefreshMetadataResponse, error)
	ListMovies(ctx context.Context, in *ListMoviesRequest, opts ...grpc.CallOption) (*ListMoviesResponse, error)
	GetMovie(ctx context.Context, in *GetMovieRequest, opts ...grpc.CallOption) (*GetMovieResponse, error)
	AddFile(ctx context.Context, in *AddFileRequest, opts ...grpc.CallOption) (*AddFileResponse, error)
	RemoveFile(ctx context.Context, in *RemoveFileRequest, opts ...grpc.CallOption) (*RemoveFileResponse, error)
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
}

type movieManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieManagementServiceClient(cc grpc.ClientConnInterface) MovieManagementServiceClient {
	return &movieManagementServiceClient{cc}
}

func (c *movieManagementServiceClient) AddMovie(ctx context.Context, in *AddMovieRequest, opts ...grpc.CallOption) (*AddMovieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMovieResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_AddMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) RemoveMovie(ctx context.Context, in *RemoveMovieRequest, opts ...grpc.CallOption) (*RemoveMovieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMovieResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_RemoveMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) RefreshMetadata(ctx context.Context, in *RefreshMetadataRequest, opts ...grpc.CallOption) (*RefreshMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshMetadataResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_RefreshMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) ListMovies(ctx context.Context, in *ListMoviesRequest, opts ...grpc.CallOption) (*ListMoviesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMoviesResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_ListMovies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) GetMovie(ctx context.Context, in *GetMovieRequest, opts ...grpc.CallOption) (*GetMovieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMovieResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_GetMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) AddFile(ctx context.Context, in *AddFileRequest, opts ...grpc.CallOption) (*AddFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFileResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_AddFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) RemoveFile(ctx context.Context, in *RemoveFileRequest, opts ...grpc.CallOption) (*RemoveFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFileResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_RemoveFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieManagementServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, MovieManagementService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieManagementServiceServer is the server API for MovieManagementService service.
// All implementations must embed UnimplementedMovieManagementServiceServer
// for forward compatibility.
type MovieManagementServiceServer interface {
	AddMovie(context.Context, *AddMovieRequest) (*AddMovieResponse, error)
	RemoveMovie(context.Context, *RemoveMovieRequest) (*RemoveMovieResponse, error)
	RefreshMetadata(context.Context, *RefreshMetadataRequest) (*RefreshMetadataResponse, error)
	ListMovies(context.Context, *ListMoviesRequest) (*ListMoviesResponse, error)
	GetMovie(context.Context, *GetMovieRequest) (*GetMovieResponse, error)
	AddFile(context.Context, *AddFileRequest) (*AddFileResponse, error)
	RemoveFile(context.Context, *RemoveFileRequest) (*RemoveFileResponse, error)
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	mustEmbedUnimplementedMovieManagementServiceServer()
}

// UnimplementedMovieManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMovieManagementServiceServer struct{}

func (UnimplementedMovieManagementServiceServer) AddMovie(context.Context, *AddMovieRequest) (*AddMovieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMovie not implemented")
}
func (UnimplementedMovieManagementServiceServer) RemoveMovie(context.Context, *RemoveMovieRequest) (*RemoveMovieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMovie not implemented")
}
func (UnimplementedMovieManagementServiceServer) RefreshMetadata(context.Context, *RefreshMetadataRequest) (*RefreshMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshMetadata not implemented")
}
func (UnimplementedMovieManagementServiceServer) ListMovies(context.Context, *ListMoviesRequest) (*ListMoviesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMovies not implemented")
}
func (UnimplementedMovieManagementServiceServer) GetMovie(context.Context, *GetMovieRequest) (*GetMovieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMovie not implemented")
}
func (UnimplementedMovieManagementServiceServer) AddFile(context.Context, *AddFileRequest) (*AddFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddFile not implemented")
}
func (UnimplementedMovieManagementServiceServer) RemoveFile(context.Context, *RemoveFileRequest) (*RemoveFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFile not implemented")
}
func (UnimplementedMovieManagementServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedMovieManagementServiceServer) mustEmbedUnimplementedMovieManagementServiceServer() {
}
func (UnimplementedMovieManagementServiceServer) testEmbeddedByValue() {}

// UnsafeMovieManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieManagementServiceServer will
// result in compilation errors.
type UnsafeMovieManagementServiceServer interface {
	mustEmbedUnimplementedMovieManagementServiceServer()
}

func RegisterMovieManagementServiceServer(s grpc.ServiceRegistrar, srv MovieManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedMovieManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MovieManagementService_ServiceDesc, srv)
}

func _MovieManagementService_AddMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).AddMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_AddMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).AddMovie(ctx, req.(*AddMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_RemoveMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).RemoveMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_RemoveMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).RemoveMovie(ctx, req.(*RemoveMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_RefreshMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).RefreshMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_RefreshMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).RefreshMetadata(ctx, req.(*RefreshMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_ListMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMoviesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).ListMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_ListMovies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).ListMovies(ctx, req.(*ListMoviesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_GetMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).GetMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_GetMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).GetMovie(ctx, req.(*GetMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_AddFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).AddFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_AddFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).AddFile(ctx, req.(*AddFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_RemoveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).RemoveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_RemoveFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).RemoveFile(ctx, req.(*RemoveFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieManagementService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieManagementServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieManagementService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieManagementServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MovieManagementService_ServiceDesc is the grpc.ServiceDesc for MovieManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovieManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muxcore.media.movies.v1.MovieManagementService",
	HandlerType: (*MovieManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMovie",
			Handler:    _MovieManagementService_AddMovie_Handler,
		},
		{
			MethodName: "RemoveMovie",
			Handler:    _MovieManagementService_RemoveMovie_Handler,
		},
		{
			MethodName: "RefreshMetadata",
			Handler:    _MovieManagementService_RefreshMetadata_Handler,
		},
		{
			MethodName: "ListMovies",
			Handler:    _MovieManagementService_ListMovies_Handler,
		},
		{
			MethodName: "GetMovie",
			Handler:    _MovieManagementService_GetMovie_Handler,
		},
		{
			MethodName: "AddFile",
			Handler:    _MovieManagementService_AddFile_Handler,
		},
		{
			MethodName: "RemoveFile",
			Handler:    _MovieManagementService_RemoveFile_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _MovieManagementService_ListFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mgmntv1/movies.proto",
}
