// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/mgmntv1/movies.proto

package mgmntv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmdbId        int32                  `protobuf:"varint,1,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Overview      string                 `protobuf:"bytes,4,opt,name=overview,proto3" json:"overview,omitempty"`
	PosterPath    string                 `protobuf:"bytes,5,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	BackdropPath  string                 `protobuf:"bytes,6,opt,name=backdrop_path,json=backdropPath,proto3" json:"backdrop_path,omitempty"`
	Genres        []string               `protobuf:"bytes,7,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMovieRequest) Reset() {
	*x = AddMovieRequest{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMovieRequest) ProtoMessage() {}

func (x *AddMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMovieRequest.ProtoReflect.Descriptor instead.
func (*AddMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{0}
}

func (x *AddMovieRequest) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *AddMovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddMovieRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *AddMovieRequest) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *AddMovieRequest) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *AddMovieRequest) GetBackdropPath() string {
	if x != nil {
		return x.BackdropPath
	}
	return ""
}

func (x *AddMovieRequest) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

type AddMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMovieResponse) Reset() {
	*x = AddMovieResponse{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMovieResponse) ProtoMessage() {}

func (x *AddMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMovieResponse.ProtoReflect.Descriptor instead.
func (*AddMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{1}
}

func (x *AddMovieResponse) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type RemoveMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMovieRequest) Reset() {
	*x = RemoveMovieRequest{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMovieRequest) ProtoMessage() {}

func (x *RemoveMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMovieRequest.ProtoReflect.Descriptor instead.
func (*RemoveMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveMovieRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type RemoveMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMovieResponse) Reset() {
	*x = RemoveMovieResponse{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMovieResponse) ProtoMessage() {}

func (x *RemoveMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMovieResponse.ProtoReflect.Descriptor instead.
func (*RemoveMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{3}
}

type RefreshMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshMetadataRequest) Reset() {
	*x = RefreshMetadataRequest{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshMetadataRequest) ProtoMessage() {}

func (x *RefreshMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshMetadataRequest.ProtoReflect.Descriptor instead.
func (*RefreshMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshMetadataRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type RefreshMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshMetadataResponse) Reset() {
	*x = RefreshMetadataResponse{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshMetadataResponse) ProtoMessage() {}

func (x *RefreshMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshMetadataResponse.ProtoReflect.Descriptor instead.
func (*RefreshMetadataResponse) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{5}
}

type ListMoviesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Genre         string                 `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	SortBy        string                 `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMoviesRequest) Reset() {
	*x = ListMoviesRequest{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMoviesRequest) ProtoMessage() {}

func (x *ListMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMoviesRequest.ProtoReflect.Descriptor instead.
func (*ListMoviesRequest) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{6}
}

func (x *ListMoviesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMoviesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMoviesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListMoviesRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *ListMoviesRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListMoviesRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type ListMoviesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*MovieItem           `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMoviesResponse) Reset() {
	*x = ListMoviesResponse{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMoviesResponse) ProtoMessage() {}

func (x *ListMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMoviesResponse.ProtoReflect.Descriptor instead.
func (*ListMoviesResponse) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{7}
}

func (x *ListMoviesResponse) GetMovies() []*MovieItem {
	if x != nil {
		return x.Movies
	}
	return nil
}

func (x *ListMoviesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListMoviesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMoviesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieRequest) Reset() {
	*x = GetMovieRequest{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieRequest) ProtoMessage() {}

func (x *GetMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieRequest.ProtoReflect.Descriptor instead.
func (*GetMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{8}
}

func (x *GetMovieRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type GetMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *MovieItem             `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieResponse) Reset() {
	*x = GetMovieResponse{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieResponse) ProtoMessage() {}

func (x *GetMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieResponse.ProtoReflect.Descriptor instead.
func (*GetMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{9}
}

func (x *GetMovieResponse) GetMovie() *MovieItem {
	if x != nil {
		return x.Movie
	}
	return nil
}

type MovieItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TmdbId        int32                  `protobuf:"varint,2,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	OriginalTitle string                 `protobuf:"bytes,4,opt,name=original_title,json=originalTitle,proto3" json:"original_title,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Overview      string                 `protobuf:"bytes,6,opt,name=overview,proto3" json:"overview,omitempty"`
	Tagline       string                 `protobuf:"bytes,7,opt,name=tagline,proto3" json:"tagline,omitempty"`
	Runtime       int32                  `protobuf:"varint,8,opt,name=runtime,proto3" json:"runtime,omitempty"`
	VoteAverage   float64                `protobuf:"fixed64,9,opt,name=vote_average,json=voteAverage,proto3" json:"vote_average,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	ImdbId        string                 `protobuf:"bytes,11,opt,name=imdb_id,json=imdbId,proto3" json:"imdb_id,omitempty"`
	Genres        []string               `protobuf:"bytes,12,rep,name=genres,proto3" json:"genres,omitempty"`
	PosterPath    string                 `protobuf:"bytes,13,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	BackdropPath  string                 `protobuf:"bytes,14,opt,name=backdrop_path,json=backdropPath,proto3" json:"backdrop_path,omitempty"`
	PosterUrl     string                 `protobuf:"bytes,15,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	BackdropUrl   string                 `protobuf:"bytes,16,opt,name=backdrop_url,json=backdropUrl,proto3" json:"backdrop_url,omitempty"`
	Monitored     bool                   `protobuf:"varint,17,opt,name=monitored,proto3" json:"monitored,omitempty"`
	HasFile       bool                   `protobuf:"varint,20,opt,name=has_file,json=hasFile,proto3" json:"has_file,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieItem) Reset() {
	*x = MovieItem{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieItem) ProtoMessage() {}

func (x *MovieItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieItem.ProtoReflect.Descriptor instead.
func (*MovieItem) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{10}
}

func (x *MovieItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MovieItem) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *MovieItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieItem) GetOriginalTitle() string {
	if x != nil {
		return x.OriginalTitle
	}
	return ""
}

func (x *MovieItem) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *MovieItem) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *MovieItem) GetTagline() string {
	if x != nil {
		return x.Tagline
	}
	return ""
}

func (x *MovieItem) GetRuntime() int32 {
	if x != nil {
		return x.Runtime
	}
	return 0
}

func (x *MovieItem) GetVoteAverage() float64 {
	if x != nil {
		return x.VoteAverage
	}
	return 0
}

func (x *MovieItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MovieItem) GetImdbId() string {
	if x != nil {
		return x.ImdbId
	}
	return ""
}

func (x *MovieItem) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MovieItem) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *MovieItem) GetBackdropPath() string {
	if x != nil {
		return x.BackdropPath
	}
	return ""
}

func (x *MovieItem) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *MovieItem) GetBackdropUrl() string {
	if x != nil {
		return x.BackdropUrl
	}
	return ""
}

func (x *MovieItem) GetMonitored() bool {
	if x != nil {
		return x.Monitored
	}
	return false
}

func (x *MovieItem) GetHasFile() bool {
	if x != nil {
		return x.HasFile
	}
	return false
}

func (x *MovieItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MovieItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AddFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Quality       string                 `protobuf:"bytes,3,opt,name=quality,proto3" json:"quality,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Container     string                 `protobuf:"bytes,5,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFileRequest) Reset() {
	*x = AddFileRequest{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFileRequest) ProtoMessage() {}

func (x *AddFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFileRequest.ProtoReflect.Descriptor instead.
func (*AddFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{11}
}

func (x *AddFileRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *AddFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *AddFileRequest) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *AddFileRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *AddFileRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

type AddFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFileResponse) Reset() {
	*x = AddFileResponse{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFileResponse) ProtoMessage() {}

func (x *AddFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFileResponse.ProtoReflect.Descriptor instead.
func (*AddFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{12}
}

func (x *AddFileResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type RemoveFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFileRequest) Reset() {
	*x = RemoveFileRequest{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileRequest) ProtoMessage() {}

func (x *RemoveFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileRequest.ProtoReflect.Descriptor instead.
func (*RemoveFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type RemoveFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFileResponse) Reset() {
	*x = RemoveFileResponse{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileResponse) ProtoMessage() {}

func (x *RemoveFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileResponse.ProtoReflect.Descriptor instead.
func (*RemoveFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{14}
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{15}
}

func (x *ListFilesRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*MovieFile           `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{16}
}

func (x *ListFilesResponse) GetFiles() []*MovieFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type MovieFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MovieId       string                 `protobuf:"bytes,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Quality       string                 `protobuf:"bytes,4,opt,name=quality,proto3" json:"quality,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Container     string                 `protobuf:"bytes,6,opt,name=container,proto3" json:"container,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieFile) Reset() {
	*x = MovieFile{}
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieFile) ProtoMessage() {}

func (x *MovieFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mgmntv1_movies_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieFile.ProtoReflect.Descriptor instead.
func (*MovieFile) Descriptor() ([]byte, []int) {
	return file_proto_mgmntv1_movies_proto_rawDescGZIP(), []int{17}
}

func (x *MovieFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MovieFile) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *MovieFile) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *MovieFile) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *MovieFile) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *MovieFile) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *MovieFile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_mgmntv1_movies_proto protoreflect.FileDescriptor

const file_proto_mgmntv1_movies_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/mgmntv1/movies.proto\x12\x17muxcore.media.movies.v1\"\xce\x01\n" +
	"\x0fAddMovieRequest\x12\x17\n" +
	"\atmdb_id\x18\x01 \x01(\x05R\x06tmdbId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x1a\n" +
	"\boverview\x18\x04 \x01(\tR\boverview\x12\x1f\n" +
	"\vposter_path\x18\x05 \x01(\tR\n" +
	"posterPath\x12#\n" +
	"\rbackdrop_path\x18\x06 \x01(\tR\fbackdropPath\x12\x16\n" +
	"\x06genres\x18\a \x03(\tR\x06genres\"-\n" +
	"\x10AddMovieResponse\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\"/\n" +
	"\x12RemoveMovieRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\"\x15\n" +
	"\x13RemoveMovieResponse\"3\n" +
	"\x16RefreshMetadataRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\"\x19\n" +
	"\x17RefreshMetadataResponse\"\xaa\x01\n" +
	"\x11ListMoviesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x14\n" +
	"\x05genre\x18\x04 \x01(\tR\x05genre\x12\x17\n" +
	"\asort_by\x18\x05 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\tR\tsortOrder\"\x97\x01\n" +
	"\x12ListMoviesResponse\x12:\n" +
	"\x06movies\x18\x01 \x03(\v2\".muxcore.media.movies.v1.MovieItemR\x06movies\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\",\n" +
	"\x0fGetMovieRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\"L\n" +
	"\x10GetMovieResponse\x128\n" +
	"\x05movie\x18\x01 \x01(\v2\".muxcore.media.movies.v1.MovieItemR\x05movie\"\xc0\x04\n" +
	"\tMovieItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atmdb_id\x18\x02 \x01(\x05R\x06tmdbId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12%\n" +
	"\x0eoriginal_title\x18\x04 \x01(\tR\roriginalTitle\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x1a\n" +
	"\boverview\x18\x06 \x01(\tR\boverview\x12\x18\n" +
	"\atagline\x18\a \x01(\tR\atagline\x12\x18\n" +
	"\aruntime\x18\b \x01(\x05R\aruntime\x12!\n" +
	"\fvote_average\x18\t \x01(\x01R\vvoteAverage\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x17\n" +
	"\aimdb_id\x18\v \x01(\tR\x06imdbId\x12\x16\n" +
	"\x06genres\x18\f \x03(\tR\x06genres\x12\x1f\n" +
	"\vposter_path\x18\r \x01(\tR\n" +
	"posterPath\x12#\n" +
	"\rbackdrop_path\x18\x0e \x01(\tR\fbackdropPath\x12\x1d\n" +
	"\n" +
	"poster_url\x18\x0f \x01(\tR\tposterUrl\x12!\n" +
	"\fbackdrop_url\x18\x10 \x01(\tR\vbackdropUrl\x12\x1c\n" +
	"\tmonitored\x18\x11 \x01(\bR\tmonitored\x12\x19\n" +
	"\bhas_file\x18\x14 \x01(\bR\ahasFile\x12\x1d\n" +
	"\n" +
	"created_at\x18\x12 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\tR\tupdatedAt\"\x9f\x01\n" +
	"\x0eAddFileRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x18\n" +
	"\aquality\x18\x03 \x01(\tR\aquality\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x1c\n" +
	"\tcontainer\x18\x05 \x01(\tR\tcontainer\"*\n" +
	"\x0fAddFileResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\",\n" +
	"\x11RemoveFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\x14\n" +
	"\x12RemoveFileResponse\"-\n" +
	"\x10ListFilesRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\"M\n" +
	"\x11ListFilesResponse\x128\n" +
	"\x05files\x18\x01 \x03(\v2\".muxcore.media.movies.v1.MovieFileR\x05files\"\xc9\x01\n" +
	"\tMovieFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\tR\amovieId\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x18\n" +
	"\aquality\x18\x04 \x01(\tR\aquality\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x1c\n" +
	"\tcontainer\x18\x06 \x01(\tR\tcontainer\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt2\xca\x06\n" +
	"\x16MovieManagementService\x12_\n" +
	"\bAddMovie\x12(.muxcore.media.movies.v1.AddMovieRequest\x1a).muxcore.media.movies.v1.AddMovieResponse\x12h\n" +
	"\vRemoveMovie\x12+.muxcore.media.movies.v1.RemoveMovieRequest\x1a,.muxcore.media.movies.v1.RemoveMovieResponse\x12t\n" +
	"\x0fRefreshMetadata\x12/.muxcore.media.movies.v1.RefreshMetadataRequest\x1a0.muxcore.media.movies.v1.RefreshMetadataResponse\x12e\n" +
	"\n" +
	"ListMovies\x12*.muxcore.media.movies.v1.ListMoviesRequest\x1a+.muxcore.media.movies.v1.ListMoviesResponse\x12_\n" +
	"\bGetMovie\x12(.muxcore.media.movies.v1.GetMovieRequest\x1a).muxcore.media.movies.v1.GetMovieResponse\x12\\\n" +
	"\aAddFile\x12'.muxcore.media.movies.v1.AddFileRequest\x1a(.muxcore.media.movies.v1.AddFileResponse\x12e\n" +
	"\n" +
	"RemoveFile\x12*.muxcore.media.movies.v1.RemoveFileRequest\x1a+.muxcore.media.movies.v1.RemoveFileResponse\x12b\n" +
	"\tListFiles\x12).muxcore.media.movies.v1.ListFilesRequest\x1a*.muxcore.media.movies.v1.ListFilesResponseB=Z;github.com/Muxcore-Media/media-movies/proto/mgmntv1;mgmntv1b\x06proto3"

var (
	file_proto_mgmntv1_movies_proto_rawDescOnce sync.Once
	file_proto_mgmntv1_movies_proto_rawDescData []byte
)

func file_proto_mgmntv1_movies_proto_rawDescGZIP() []byte {
	file_proto_mgmntv1_movies_proto_rawDescOnce.Do(func() {
		file_proto_mgmntv1_movies_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mgmntv1_movies_proto_rawDesc), len(file_proto_mgmntv1_movies_proto_rawDesc)))
	})
	return file_proto_mgmntv1_movies_proto_rawDescData
}

var file_proto_mgmntv1_movies_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_mgmntv1_movies_proto_goTypes = []any{
	(*AddMovieRequest)(nil),         // 0: muxcore.media.movies.v1.AddMovieRequest
	(*AddMovieResponse)(nil),        // 1: muxcore.media.movies.v1.AddMovieResponse
	(*RemoveMovieRequest)(nil),      // 2: muxcore.media.movies.v1.RemoveMovieRequest
	(*RemoveMovieResponse)(nil),     // 3: muxcore.media.movies.v1.RemoveMovieResponse
	(*RefreshMetadataRequest)(nil),  // 4: muxcore.media.movies.v1.RefreshMetadataRequest
	(*RefreshMetadataResponse)(nil), // 5: muxcore.media.movies.v1.RefreshMetadataResponse
	(*ListMoviesRequest)(nil),       // 6: muxcore.media.movies.v1.ListMoviesRequest
	(*ListMoviesResponse)(nil),      // 7: muxcore.media.movies.v1.ListMoviesResponse
	(*GetMovieRequest)(nil),         // 8: muxcore.media.movies.v1.GetMovieRequest
	(*GetMovieResponse)(nil),        // 9: muxcore.media.movies.v1.GetMovieResponse
	(*MovieItem)(nil),               // 10: muxcore.media.movies.v1.MovieItem
	(*AddFileRequest)(nil),          // 11: muxcore.media.movies.v1.AddFileRequest
	(*AddFileResponse)(nil),         // 12: muxcore.media.movies.v1.AddFileResponse
	(*RemoveFileRequest)(nil),       // 13: muxcore.media.movies.v1.RemoveFileRequest
	(*RemoveFileResponse)(nil),      // 14: muxcore.media.movies.v1.RemoveFileResponse
	(*ListFilesRequest)(nil),        // 15: muxcore.media.movies.v1.ListFilesRequest
	(*ListFilesResponse)(nil),       // 16: muxcore.media.movies.v1.ListFilesResponse
	(*MovieFile)(nil),               // 17: muxcore.media.movies.v1.MovieFile
}
var file_proto_mgmntv1_movies_proto_depIdxs = []int32{
	10, // 0: muxcore.media.movies.v1.ListMoviesResponse.movies:type_name -> muxcore.media.movies.v1.MovieItem
	10, // 1: muxcore.media.movies.v1.GetMovieResponse.movie:type_name -> muxcore.media.movies.v1.MovieItem
	17, // 2: muxcore.media.movies.v1.ListFilesResponse.files:type_name -> muxcore.media.movies.v1.MovieFile
	0,  // 3: muxcore.media.movies.v1.MovieManagementService.AddMovie:input_type -> muxcore.media.movies.v1.AddMovieRequest
	2,  // 4: muxcore.media.movies.v1.MovieManagementService.RemoveMovie:input_type -> muxcore.media.movies.v1.RemoveMovieRequest
	4,  // 5: muxcore.media.movies.v1.MovieManagementService.RefreshMetadata:input_type -> muxcore.media.movies.v1.RefreshMetadataRequest
	6,  // 6: muxcore.media.movies.v1.MovieManagementService.ListMovies:input_type -> muxcore.media.movies.v1.ListMoviesRequest
	8,  // 7: muxcore.media.movies.v1.MovieManagementService.GetMovie:input_type -> muxcore.media.movies.v1.GetMovieRequest
	11, // 8: muxcore.media.movies.v1.MovieManagementService.AddFile:input_type -> muxcore.media.movies.v1.AddFileRequest
	13, // 9: muxcore.media.movies.v1.MovieManagementService.RemoveFile:input_type -> muxcore.media.movies.v1.RemoveFileRequest
	15, // 10: muxcore.media.movies.v1.MovieManagementService.ListFiles:input_type -> muxcore.media.movies.v1.ListFilesRequest
	1,  // 11: muxcore.media.movies.v1.MovieManagementService.AddMovie:output_type -> muxcore.media.movies.v1.AddMovieResponse
	3,  // 12: muxcore.media.movies.v1.MovieManagementService.RemoveMovie:output_type -> muxcore.media.movies.v1.RemoveMovieResponse
	5,  // 13: muxcore.media.movies.v1.MovieManagementService.RefreshMetadata:output_type -> muxcore.media.movies.v1.RefreshMetadataResponse
	7,  // 14: muxcore.media.movies.v1.MovieManagementService.ListMovies:output_type -> muxcore.media.movies.v1.ListMoviesResponse
	9,  // 15: muxcore.media.movies.v1.MovieManagementService.GetMovie:output_type -> muxcore.media.movies.v1.GetMovieResponse
	12, // 16: muxcore.media.movies.v1.MovieManagementService.AddFile:output_type -> muxcore.media.movies.v1.AddFileResponse
	14, // 17: muxcore.media.movies.v1.MovieManagementService.RemoveFile:output_type -> muxcore.media.movies.v1.RemoveFileResponse
	16, // 18: muxcore.media.movies.v1.MovieManagementService.ListFiles:output_type -> muxcore.media.movies.v1.ListFilesResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_mgmntv1_movies_proto_init() }
func file_proto_mgmntv1_movies_proto_init() {
	if File_proto_mgmntv1_movies_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mgmntv1_movies_proto_rawDesc), len(file_proto_mgmntv1_movies_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mgmntv1_movies_proto_goTypes,
		DependencyIndexes: file_proto_mgmntv1_movies_proto_depIdxs,
		MessageInfos:      file_proto_mgmntv1_movies_proto_msgTypes,
	}.Build()
	File_proto_mgmntv1_movies_proto = out.File
	file_proto_mgmntv1_movies_proto_goTypes = nil
	file_proto_mgmntv1_movies_proto_depIdxs = nil
}
